/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
public enum ActivityHistory_StatusEnum {

    // Completed
    COMPLETED("Completed"),
    // Deferred
    DEFERRED("Deferred"),
    // In Progress
    IN_PROGRESS("In Progress"),
    // Not Started
    NOT_STARTED("Not Started"),
    // Waiting on someone else
    WAITING_ON_SOMEONE_ELSE("Waiting on someone else");

    final String value;

    private ActivityHistory_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ActivityHistory_StatusEnum fromValue(String value) {
        for (ActivityHistory_StatusEnum e : ActivityHistory_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
