/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Method
 */
public enum ActionLinkTemplate_MethodEnum {

    // HttpDelete
    HTTPDELETE("HttpDelete"),
    // HttpGet
    HTTPGET("HttpGet"),
    // HttpHead
    HTTPHEAD("HttpHead"),
    // HttpPatch
    HTTPPATCH("HttpPatch"),
    // HttpPost
    HTTPPOST("HttpPost"),
    // HttpPut
    HTTPPUT("HttpPut");

    final String value;

    private ActionLinkTemplate_MethodEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ActionLinkTemplate_MethodEnum fromValue(String value) {
        for (ActionLinkTemplate_MethodEnum e : ActionLinkTemplate_MethodEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
