/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist LinkType
 */
public enum ActionLinkTemplate_LinkTypeEnum {

    // API
    API("API"),
    // APIAsync
    APIASYNC("APIAsync"),
    // Download
    DOWNLOAD("Download"),
    // UI
    UI("UI");

    final String value;

    private ActionLinkTemplate_LinkTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ActionLinkTemplate_LinkTypeEnum fromValue(String value) {
        for (ActionLinkTemplate_LinkTypeEnum e : ActionLinkTemplate_LinkTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
