/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
public enum ApexTrigger_StatusEnum {

    // Active
    ACTIVE("Active"),
    // Deleted
    DELETED("Deleted"),
    // Inactive
    INACTIVE("Inactive");

    final String value;

    private ApexTrigger_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ApexTrigger_StatusEnum fromValue(String value) {
        for (ApexTrigger_StatusEnum e : ApexTrigger_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
