/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
public enum ApexTestQueueItem_StatusEnum {

    // Aborted
    ABORTED("Aborted"),
    // Completed
    COMPLETED("Completed"),
    // Failed
    FAILED("Failed"),
    // Holding
    HOLDING("Holding"),
    // Preparing
    PREPARING("Preparing"),
    // Processing
    PROCESSING("Processing"),
    // Queued
    QUEUED("Queued");

    final String value;

    private ApexTestQueueItem_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ApexTestQueueItem_StatusEnum fromValue(String value) {
        for (ApexTestQueueItem_StatusEnum e : ApexTestQueueItem_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
