/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist JobType
 */
public enum AsyncApexJob_JobTypeEnum {

    // ApexToken
    APEXTOKEN("ApexToken"),
    // BatchApex
    BATCHAPEX("BatchApex"),
    // BatchApexWorker
    BATCHAPEXWORKER("BatchApexWorker"),
    // Future
    FUTURE("Future"),
    // Queueable
    QUEUEABLE("Queueable"),
    // ScheduledApex
    SCHEDULEDAPEX("ScheduledApex"),
    // SharingRecalculation
    SHARINGRECALCULATION("SharingRecalculation"),
    // TestRequest
    TESTREQUEST("TestRequest"),
    // TestWorker
    TESTWORKER("TestWorker");

    final String value;

    private AsyncApexJob_JobTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static AsyncApexJob_JobTypeEnum fromValue(String value) {
        for (AsyncApexJob_JobTypeEnum e : AsyncApexJob_JobTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
