/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject AuraDefinition
 */
@XStreamAlias("AuraDefinition")
public class AuraDefinition extends AbstractSObjectBase {

    // AuraDefinitionBundleId
    private String AuraDefinitionBundleId;

    @JsonProperty("AuraDefinitionBundleId")
    public String getAuraDefinitionBundleId() {
        return this.AuraDefinitionBundleId;
    }

    @JsonProperty("AuraDefinitionBundleId")
    public void setAuraDefinitionBundleId(String AuraDefinitionBundleId) {
        this.AuraDefinitionBundleId = AuraDefinitionBundleId;
    }

    // DefType
    @XStreamConverter(PicklistEnumConverter.class)
    private AuraDefinition_DefTypeEnum DefType;

    @JsonProperty("DefType")
    public AuraDefinition_DefTypeEnum getDefType() {
        return this.DefType;
    }

    @JsonProperty("DefType")
    public void setDefType(AuraDefinition_DefTypeEnum DefType) {
        this.DefType = DefType;
    }

    // Format
    @XStreamConverter(PicklistEnumConverter.class)
    private AuraDefinition_FormatEnum Format;

    @JsonProperty("Format")
    public AuraDefinition_FormatEnum getFormat() {
        return this.Format;
    }

    @JsonProperty("Format")
    public void setFormat(AuraDefinition_FormatEnum Format) {
        this.Format = Format;
    }

    // Source
    private String Source;

    @JsonProperty("Source")
    public String getSource() {
        return this.Source;
    }

    @JsonProperty("Source")
    public void setSource(String Source) {
        this.Source = Source;
    }

}
