/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject AuthSession
 */
@XStreamAlias("AuthSession")
public class AuthSession extends AbstractSObjectBase {

    // UsersId
    private String UsersId;

    @JsonProperty("UsersId")
    public String getUsersId() {
        return this.UsersId;
    }

    @JsonProperty("UsersId")
    public void setUsersId(String UsersId) {
        this.UsersId = UsersId;
    }

    // NumSecondsValid
    private Integer NumSecondsValid;

    @JsonProperty("NumSecondsValid")
    public Integer getNumSecondsValid() {
        return this.NumSecondsValid;
    }

    @JsonProperty("NumSecondsValid")
    public void setNumSecondsValid(Integer NumSecondsValid) {
        this.NumSecondsValid = NumSecondsValid;
    }

    // UserType
    @XStreamConverter(PicklistEnumConverter.class)
    private AuthSession_UserTypeEnum UserType;

    @JsonProperty("UserType")
    public AuthSession_UserTypeEnum getUserType() {
        return this.UserType;
    }

    @JsonProperty("UserType")
    public void setUserType(AuthSession_UserTypeEnum UserType) {
        this.UserType = UserType;
    }

    // SourceIp
    private String SourceIp;

    @JsonProperty("SourceIp")
    public String getSourceIp() {
        return this.SourceIp;
    }

    @JsonProperty("SourceIp")
    public void setSourceIp(String SourceIp) {
        this.SourceIp = SourceIp;
    }

    // LoginType
    @XStreamConverter(PicklistEnumConverter.class)
    private AuthSession_LoginTypeEnum LoginType;

    @JsonProperty("LoginType")
    public AuthSession_LoginTypeEnum getLoginType() {
        return this.LoginType;
    }

    @JsonProperty("LoginType")
    public void setLoginType(AuthSession_LoginTypeEnum LoginType) {
        this.LoginType = LoginType;
    }

    // SessionType
    @XStreamConverter(PicklistEnumConverter.class)
    private AuthSession_SessionTypeEnum SessionType;

    @JsonProperty("SessionType")
    public AuthSession_SessionTypeEnum getSessionType() {
        return this.SessionType;
    }

    @JsonProperty("SessionType")
    public void setSessionType(AuthSession_SessionTypeEnum SessionType) {
        this.SessionType = SessionType;
    }

    // SessionSecurityLevel
    @XStreamConverter(PicklistEnumConverter.class)
    private AuthSession_SessionSecurityLevelEnum SessionSecurityLevel;

    @JsonProperty("SessionSecurityLevel")
    public AuthSession_SessionSecurityLevelEnum getSessionSecurityLevel() {
        return this.SessionSecurityLevel;
    }

    @JsonProperty("SessionSecurityLevel")
    public void setSessionSecurityLevel(AuthSession_SessionSecurityLevelEnum SessionSecurityLevel) {
        this.SessionSecurityLevel = SessionSecurityLevel;
    }

    // LogoutUrl
    private String LogoutUrl;

    @JsonProperty("LogoutUrl")
    public String getLogoutUrl() {
        return this.LogoutUrl;
    }

    @JsonProperty("LogoutUrl")
    public void setLogoutUrl(String LogoutUrl) {
        this.LogoutUrl = LogoutUrl;
    }

    // ParentId
    private String ParentId;

    @JsonProperty("ParentId")
    public String getParentId() {
        return this.ParentId;
    }

    @JsonProperty("ParentId")
    public void setParentId(String ParentId) {
        this.ParentId = ParentId;
    }

    // LoginHistoryId
    private String LoginHistoryId;

    @JsonProperty("LoginHistoryId")
    public String getLoginHistoryId() {
        return this.LoginHistoryId;
    }

    @JsonProperty("LoginHistoryId")
    public void setLoginHistoryId(String LoginHistoryId) {
        this.LoginHistoryId = LoginHistoryId;
    }

}
