/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Role
 */
public enum CaseContactRole_RoleEnum {

    // Business Contact
    BUSINESS_CONTACT("Business Contact"),
    // Decision Maker
    DECISION_MAKER("Decision Maker"),
    // Other
    OTHER("Other"),
    // Technical Contact
    TECHNICAL_CONTACT("Technical Contact");

    final String value;

    private CaseContactRole_RoleEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static CaseContactRole_RoleEnum fromValue(String value) {
        for (CaseContactRole_RoleEnum e : CaseContactRole_RoleEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
