/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject CaseTeamTemplateMember
 */
@XStreamAlias("CaseTeamTemplateMember")
public class CaseTeamTemplateMember extends AbstractSObjectBase {

    // TeamTemplateId
    private String TeamTemplateId;

    @JsonProperty("TeamTemplateId")
    public String getTeamTemplateId() {
        return this.TeamTemplateId;
    }

    @JsonProperty("TeamTemplateId")
    public void setTeamTemplateId(String TeamTemplateId) {
        this.TeamTemplateId = TeamTemplateId;
    }

    // MemberId
    private String MemberId;

    @JsonProperty("MemberId")
    public String getMemberId() {
        return this.MemberId;
    }

    @JsonProperty("MemberId")
    public void setMemberId(String MemberId) {
        this.MemberId = MemberId;
    }

    // TeamRoleId
    private String TeamRoleId;

    @JsonProperty("TeamRoleId")
    public String getTeamRoleId() {
        return this.TeamRoleId;
    }

    @JsonProperty("TeamRoleId")
    public void setTeamRoleId(String TeamRoleId) {
        this.TeamRoleId = TeamRoleId;
    }

}
