/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject CaseShare
 */
@XStreamAlias("CaseShare")
public class CaseShare extends AbstractSObjectBase {

    // CaseId
    private String CaseId;

    @JsonProperty("CaseId")
    public String getCaseId() {
        return this.CaseId;
    }

    @JsonProperty("CaseId")
    public void setCaseId(String CaseId) {
        this.CaseId = CaseId;
    }

    // UserOrGroupId
    private String UserOrGroupId;

    @JsonProperty("UserOrGroupId")
    public String getUserOrGroupId() {
        return this.UserOrGroupId;
    }

    @JsonProperty("UserOrGroupId")
    public void setUserOrGroupId(String UserOrGroupId) {
        this.UserOrGroupId = UserOrGroupId;
    }

    // CaseAccessLevel
    @XStreamConverter(PicklistEnumConverter.class)
    private CaseShare_CaseAccessLevelEnum CaseAccessLevel;

    @JsonProperty("CaseAccessLevel")
    public CaseShare_CaseAccessLevelEnum getCaseAccessLevel() {
        return this.CaseAccessLevel;
    }

    @JsonProperty("CaseAccessLevel")
    public void setCaseAccessLevel(CaseShare_CaseAccessLevelEnum CaseAccessLevel) {
        this.CaseAccessLevel = CaseAccessLevel;
    }

    // RowCause
    @XStreamConverter(PicklistEnumConverter.class)
    private CaseShare_RowCauseEnum RowCause;

    @JsonProperty("RowCause")
    public CaseShare_RowCauseEnum getRowCause() {
        return this.RowCause;
    }

    @JsonProperty("RowCause")
    public void setRowCause(CaseShare_RowCauseEnum RowCause) {
        this.RowCause = RowCause;
    }

}
