/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist CollaborationType
 */
public enum CollaborationGroup_CollaborationTypeEnum {

    // Private
    PRIVATE("Private"),
    // Public
    PUBLIC("Public");

    final String value;

    private CollaborationGroup_CollaborationTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static CollaborationGroup_CollaborationTypeEnum fromValue(String value) {
        for (CollaborationGroup_CollaborationTypeEnum e : CollaborationGroup_CollaborationTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
