/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist ContactStatusDataDotCom
 */
public enum ContactCleanInfo_ContactStatusDataDotComEnum {

    // CompanyNeverExistedDataDotCom
    COMPANYNEVEREXISTEDDATADOTCOM("CompanyNeverExistedDataDotCom"),
    // CompanyOutOfBusinessDataDotCom
    COMPANYOUTOFBUSINESSDATADOTCOM("CompanyOutOfBusinessDataDotCom"),
    // DeadEmailDomainDataDotCom
    DEADEMAILDOMAINDATADOTCOM("DeadEmailDomainDataDotCom"),
    // InactiveDataDotCom
    INACTIVEDATADOTCOM("InactiveDataDotCom"),
    // IsActiveContactDataDotCom
    ISACTIVECONTACTDATADOTCOM("IsActiveContactDataDotCom"),
    // NotAtCompanyContactDataDotCom
    NOTATCOMPANYCONTACTDATADOTCOM("NotAtCompanyContactDataDotCom"),
    // WrongEmailDataDotCom
    WRONGEMAILDATADOTCOM("WrongEmailDataDotCom"),
    // WrongPhoneAndEmailDataDotCom
    WRONGPHONEANDEMAILDATADOTCOM("WrongPhoneAndEmailDataDotCom"),
    // WrongPhoneDataDotCom
    WRONGPHONEDATADOTCOM("WrongPhoneDataDotCom");

    final String value;

    private ContactCleanInfo_ContactStatusDataDotComEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ContactCleanInfo_ContactStatusDataDotComEnum fromValue(String value) {
        for (ContactCleanInfo_ContactStatusDataDotComEnum e : ContactCleanInfo_ContactStatusDataDotComEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
