/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist TagModel
 */
public enum ContentWorkspace_TagModelEnum {

    // G
    G("G"),
    // R
    R("R"),
    // U
    U("U");

    final String value;

    private ContentWorkspace_TagModelEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ContentWorkspace_TagModelEnum fromValue(String value) {
        for (ContentWorkspace_TagModelEnum e : ContentWorkspace_TagModelEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
