/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject ContactShare
 */
@XStreamAlias("ContactShare")
public class ContactShare extends AbstractSObjectBase {

    // ContactId
    private String ContactId;

    @JsonProperty("ContactId")
    public String getContactId() {
        return this.ContactId;
    }

    @JsonProperty("ContactId")
    public void setContactId(String ContactId) {
        this.ContactId = ContactId;
    }

    // UserOrGroupId
    private String UserOrGroupId;

    @JsonProperty("UserOrGroupId")
    public String getUserOrGroupId() {
        return this.UserOrGroupId;
    }

    @JsonProperty("UserOrGroupId")
    public void setUserOrGroupId(String UserOrGroupId) {
        this.UserOrGroupId = UserOrGroupId;
    }

    // ContactAccessLevel
    @XStreamConverter(PicklistEnumConverter.class)
    private ContactShare_ContactAccessLevelEnum ContactAccessLevel;

    @JsonProperty("ContactAccessLevel")
    public ContactShare_ContactAccessLevelEnum getContactAccessLevel() {
        return this.ContactAccessLevel;
    }

    @JsonProperty("ContactAccessLevel")
    public void setContactAccessLevel(ContactShare_ContactAccessLevelEnum ContactAccessLevel) {
        this.ContactAccessLevel = ContactAccessLevel;
    }

    // RowCause
    @XStreamConverter(PicklistEnumConverter.class)
    private ContactShare_RowCauseEnum RowCause;

    @JsonProperty("RowCause")
    public ContactShare_RowCauseEnum getRowCause() {
        return this.RowCause;
    }

    @JsonProperty("RowCause")
    public void setRowCause(ContactShare_RowCauseEnum RowCause) {
        this.RowCause = RowCause;
    }

}
