/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist JobType
 */
public enum CronJobDetail_JobTypeEnum {

    // 1
    _1("1"),
    // 3
    _3("3"),
    // 4
    _4("4"),
    // 7
    _7("7"),
    // 8
    _8("8"),
    // 9
    _9("9"),
    // A
    A("A");

    final String value;

    private CronJobDetail_JobTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static CronJobDetail_JobTypeEnum fromValue(String value) {
        for (CronJobDetail_JobTypeEnum e : CronJobDetail_JobTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
