/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject CronTrigger
 */
@XStreamAlias("CronTrigger")
public class CronTrigger extends AbstractSObjectBase {

    // CronJobDetailId
    private String CronJobDetailId;

    @JsonProperty("CronJobDetailId")
    public String getCronJobDetailId() {
        return this.CronJobDetailId;
    }

    @JsonProperty("CronJobDetailId")
    public void setCronJobDetailId(String CronJobDetailId) {
        this.CronJobDetailId = CronJobDetailId;
    }

    // NextFireTime
    private java.time.ZonedDateTime NextFireTime;

    @JsonProperty("NextFireTime")
    public java.time.ZonedDateTime getNextFireTime() {
        return this.NextFireTime;
    }

    @JsonProperty("NextFireTime")
    public void setNextFireTime(java.time.ZonedDateTime NextFireTime) {
        this.NextFireTime = NextFireTime;
    }

    // PreviousFireTime
    private java.time.ZonedDateTime PreviousFireTime;

    @JsonProperty("PreviousFireTime")
    public java.time.ZonedDateTime getPreviousFireTime() {
        return this.PreviousFireTime;
    }

    @JsonProperty("PreviousFireTime")
    public void setPreviousFireTime(java.time.ZonedDateTime PreviousFireTime) {
        this.PreviousFireTime = PreviousFireTime;
    }

    // State
    private String State;

    @JsonProperty("State")
    public String getState() {
        return this.State;
    }

    @JsonProperty("State")
    public void setState(String State) {
        this.State = State;
    }

    // StartTime
    private java.time.ZonedDateTime StartTime;

    @JsonProperty("StartTime")
    public java.time.ZonedDateTime getStartTime() {
        return this.StartTime;
    }

    @JsonProperty("StartTime")
    public void setStartTime(java.time.ZonedDateTime StartTime) {
        this.StartTime = StartTime;
    }

    // EndTime
    private java.time.ZonedDateTime EndTime;

    @JsonProperty("EndTime")
    public java.time.ZonedDateTime getEndTime() {
        return this.EndTime;
    }

    @JsonProperty("EndTime")
    public void setEndTime(java.time.ZonedDateTime EndTime) {
        this.EndTime = EndTime;
    }

    // CronExpression
    private String CronExpression;

    @JsonProperty("CronExpression")
    public String getCronExpression() {
        return this.CronExpression;
    }

    @JsonProperty("CronExpression")
    public void setCronExpression(String CronExpression) {
        this.CronExpression = CronExpression;
    }

    // TimeZoneSidKey
    @XStreamConverter(PicklistEnumConverter.class)
    private CronTrigger_TimeZoneSidKeyEnum TimeZoneSidKey;

    @JsonProperty("TimeZoneSidKey")
    public CronTrigger_TimeZoneSidKeyEnum getTimeZoneSidKey() {
        return this.TimeZoneSidKey;
    }

    @JsonProperty("TimeZoneSidKey")
    public void setTimeZoneSidKey(CronTrigger_TimeZoneSidKeyEnum TimeZoneSidKey) {
        this.TimeZoneSidKey = TimeZoneSidKey;
    }

    // TimesTriggered
    private Integer TimesTriggered;

    @JsonProperty("TimesTriggered")
    public Integer getTimesTriggered() {
        return this.TimesTriggered;
    }

    @JsonProperty("TimesTriggered")
    public void setTimesTriggered(Integer TimesTriggered) {
        this.TimesTriggered = TimesTriggered;
    }

}
