/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject CustomObjectUserLicenseMetrics
 */
@XStreamAlias("CustomObjectUserLicenseMetrics")
public class CustomObjectUserLicenseMetrics extends AbstractSObjectBase {

    // MetricsDate
    private java.time.ZonedDateTime MetricsDate;

    @JsonProperty("MetricsDate")
    public java.time.ZonedDateTime getMetricsDate() {
        return this.MetricsDate;
    }

    @JsonProperty("MetricsDate")
    public void setMetricsDate(java.time.ZonedDateTime MetricsDate) {
        this.MetricsDate = MetricsDate;
    }

    // UserLicenseId
    private String UserLicenseId;

    @JsonProperty("UserLicenseId")
    public String getUserLicenseId() {
        return this.UserLicenseId;
    }

    @JsonProperty("UserLicenseId")
    public void setUserLicenseId(String UserLicenseId) {
        this.UserLicenseId = UserLicenseId;
    }

    // CustomObjectId
    private String CustomObjectId;

    @JsonProperty("CustomObjectId")
    public String getCustomObjectId() {
        return this.CustomObjectId;
    }

    @JsonProperty("CustomObjectId")
    public void setCustomObjectId(String CustomObjectId) {
        this.CustomObjectId = CustomObjectId;
    }

    // CustomObjectType
    @XStreamConverter(PicklistEnumConverter.class)
    private CustomObjectUserLicenseMetrics_CustomObjectTypeEnum CustomObjectType;

    @JsonProperty("CustomObjectType")
    public CustomObjectUserLicenseMetrics_CustomObjectTypeEnum getCustomObjectType() {
        return this.CustomObjectType;
    }

    @JsonProperty("CustomObjectType")
    public void setCustomObjectType(CustomObjectUserLicenseMetrics_CustomObjectTypeEnum CustomObjectType) {
        this.CustomObjectType = CustomObjectType;
    }

    // CustomObjectName
    private String CustomObjectName;

    @JsonProperty("CustomObjectName")
    public String getCustomObjectName() {
        return this.CustomObjectName;
    }

    @JsonProperty("CustomObjectName")
    public void setCustomObjectName(String CustomObjectName) {
        this.CustomObjectName = CustomObjectName;
    }

    // ObjectCount
    private Integer ObjectCount;

    @JsonProperty("ObjectCount")
    public Integer getObjectCount() {
        return this.ObjectCount;
    }

    @JsonProperty("ObjectCount")
    public void setObjectCount(Integer ObjectCount) {
        this.ObjectCount = ObjectCount;
    }

}
