/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Subsidiary
 */
public enum DandBCompany_SubsidiaryEnum {

    // 0
    _0("0"),
    // 3
    _3("3");

    final String value;

    private DandBCompany_SubsidiaryEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DandBCompany_SubsidiaryEnum fromValue(String value) {
        for (DandBCompany_SubsidiaryEnum e : DandBCompany_SubsidiaryEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
