/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist MarketingPreScreen
 */
public enum DandBCompany_MarketingPreScreenEnum {

    // H
    H("H"),
    // L
    L("L"),
    // M
    M("M");

    final String value;

    private DandBCompany_MarketingPreScreenEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DandBCompany_MarketingPreScreenEnum fromValue(String value) {
        for (DandBCompany_MarketingPreScreenEnum e : DandBCompany_MarketingPreScreenEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
