/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist RightSize
 */
public enum Dashboard_RightSizeEnum {

    // Medium
    MEDIUM("Medium"),
    // Narrow
    NARROW("Narrow"),
    // Wide
    WIDE("Wide");

    final String value;

    private Dashboard_RightSizeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Dashboard_RightSizeEnum fromValue(String value) {
        for (Dashboard_RightSizeEnum e : Dashboard_RightSizeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
