/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Type
 */
public enum Dashboard_TypeEnum {

    // LoggedInUser
    LOGGEDINUSER("LoggedInUser"),
    // MyTeamUser
    MYTEAMUSER("MyTeamUser"),
    // SpecifiedUser
    SPECIFIEDUSER("SpecifiedUser");

    final String value;

    private Dashboard_TypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Dashboard_TypeEnum fromValue(String value) {
        for (Dashboard_TypeEnum e : Dashboard_TypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
