/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Department
 */
public enum DatacloudContact_DepartmentEnum {

    // Engineering
    ENGINEERING("Engineering"),
    // Finance
    FINANCE("Finance"),
    // HR
    HR("HR"),
    // IT
    IT("IT"),
    // Marketing
    MARKETING("Marketing"),
    // Operations
    OPERATIONS("Operations"),
    // Other
    OTHER("Other"),
    // Sales
    SALES("Sales"),
    // Support
    SUPPORT("Support");

    final String value;

    private DatacloudContact_DepartmentEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DatacloudContact_DepartmentEnum fromValue(String value) {
        for (DatacloudContact_DepartmentEnum e : DatacloudContact_DepartmentEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
