/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Level
 */
public enum DatacloudContact_LevelEnum {

    // C-Level
    C_LEVEL("C-Level"),
    // Director
    DIRECTOR("Director"),
    // Manager
    MANAGER("Manager"),
    // Other
    OTHER("Other"),
    // Staff
    STAFF("Staff"),
    // VP
    VP("VP");

    final String value;

    private DatacloudContact_LevelEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DatacloudContact_LevelEnum fromValue(String value) {
        for (DatacloudContact_LevelEnum e : DatacloudContact_LevelEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
