/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject DatacloudAddress
 */
@XStreamAlias("DatacloudAddress")
public class DatacloudAddress extends AbstractSObjectBase {

    // ExternalId
    private String ExternalId;

    @JsonProperty("ExternalId")
    public String getExternalId() {
        return this.ExternalId;
    }

    @JsonProperty("ExternalId")
    public void setExternalId(String ExternalId) {
        this.ExternalId = ExternalId;
    }

    // AddressLine1
    private String AddressLine1;

    @JsonProperty("AddressLine1")
    public String getAddressLine1() {
        return this.AddressLine1;
    }

    @JsonProperty("AddressLine1")
    public void setAddressLine1(String AddressLine1) {
        this.AddressLine1 = AddressLine1;
    }

    // AddressLine2
    private String AddressLine2;

    @JsonProperty("AddressLine2")
    public String getAddressLine2() {
        return this.AddressLine2;
    }

    @JsonProperty("AddressLine2")
    public void setAddressLine2(String AddressLine2) {
        this.AddressLine2 = AddressLine2;
    }

    // City
    private String City;

    @JsonProperty("City")
    public String getCity() {
        return this.City;
    }

    @JsonProperty("City")
    public void setCity(String City) {
        this.City = City;
    }

    // State
    private String State;

    @JsonProperty("State")
    public String getState() {
        return this.State;
    }

    @JsonProperty("State")
    public void setState(String State) {
        this.State = State;
    }

    // Country
    private String Country;

    @JsonProperty("Country")
    public String getCountry() {
        return this.Country;
    }

    @JsonProperty("Country")
    public void setCountry(String Country) {
        this.Country = Country;
    }

    // PostalCode
    private String PostalCode;

    @JsonProperty("PostalCode")
    public String getPostalCode() {
        return this.PostalCode;
    }

    @JsonProperty("PostalCode")
    public void setPostalCode(String PostalCode) {
        this.PostalCode = PostalCode;
    }

    // Latitude
    private String Latitude;

    @JsonProperty("Latitude")
    public String getLatitude() {
        return this.Latitude;
    }

    @JsonProperty("Latitude")
    public void setLatitude(String Latitude) {
        this.Latitude = Latitude;
    }

    // Longitude
    private String Longitude;

    @JsonProperty("Longitude")
    public String getLongitude() {
        return this.Longitude;
    }

    @JsonProperty("Longitude")
    public void setLongitude(String Longitude) {
        this.Longitude = Longitude;
    }

    // GeoAccuracyCode
    private String GeoAccuracyCode;

    @JsonProperty("GeoAccuracyCode")
    public String getGeoAccuracyCode() {
        return this.GeoAccuracyCode;
    }

    @JsonProperty("GeoAccuracyCode")
    public void setGeoAccuracyCode(String GeoAccuracyCode) {
        this.GeoAccuracyCode = GeoAccuracyCode;
    }

    // GeoAccuracyNum
    private String GeoAccuracyNum;

    @JsonProperty("GeoAccuracyNum")
    public String getGeoAccuracyNum() {
        return this.GeoAccuracyNum;
    }

    @JsonProperty("GeoAccuracyNum")
    public void setGeoAccuracyNum(String GeoAccuracyNum) {
        this.GeoAccuracyNum = GeoAccuracyNum;
    }

}
