/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject Domain
 */
@XStreamAlias("Domain")
public class Domain extends AbstractSObjectBase {

    // DomainType
    @XStreamConverter(PicklistEnumConverter.class)
    private Domain_DomainTypeEnum DomainType;

    @JsonProperty("DomainType")
    public Domain_DomainTypeEnum getDomainType() {
        return this.DomainType;
    }

    @JsonProperty("DomainType")
    public void setDomainType(Domain_DomainTypeEnum DomainType) {
        this.DomainType = DomainType;
    }

    // Domain
    private String Domain;

    @JsonProperty("Domain")
    public String getDomain() {
        return this.Domain;
    }

    @JsonProperty("Domain")
    public void setDomain(String Domain) {
        this.Domain = Domain;
    }

    // OptionsExternalHttps
    private Boolean OptionsExternalHttps;

    @JsonProperty("OptionsExternalHttps")
    public Boolean getOptionsExternalHttps() {
        return this.OptionsExternalHttps;
    }

    @JsonProperty("OptionsExternalHttps")
    public void setOptionsExternalHttps(Boolean OptionsExternalHttps) {
        this.OptionsExternalHttps = OptionsExternalHttps;
    }

}
