/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist TemplateType
 */
public enum EmailTemplate_TemplateTypeEnum {

    // custom
    CUSTOM("custom"),
    // html
    HTML("html"),
    // text
    TEXT("text"),
    // visualforce
    VISUALFORCE("visualforce");

    final String value;

    private EmailTemplate_TemplateTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static EmailTemplate_TemplateTypeEnum fromValue(String value) {
        for (EmailTemplate_TemplateTypeEnum e : EmailTemplate_TemplateTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
