/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist EventType
 */
public enum EventLogFile_EventTypeEnum {

    // API
    API("API"),
    // ApexCallout
    APEXCALLOUT("ApexCallout"),
    // ApexExecution
    APEXEXECUTION("ApexExecution"),
    // ApexSoap
    APEXSOAP("ApexSoap"),
    // ApexTrigger
    APEXTRIGGER("ApexTrigger"),
    // AsyncReportRun
    ASYNCREPORTRUN("AsyncReportRun"),
    // BulkApi
    BULKAPI("BulkApi"),
    // ChangeSetOperation
    CHANGESETOPERATION("ChangeSetOperation"),
    // Console
    CONSOLE("Console"),
    // ContentDistribution
    CONTENTDISTRIBUTION("ContentDistribution"),
    // ContentDocumentLink
    CONTENTDOCUMENTLINK("ContentDocumentLink"),
    // ContentTransfer
    CONTENTTRANSFER("ContentTransfer"),
    // Dashboard
    DASHBOARD("Dashboard"),
    // DocumentAttachmentDownloads
    DOCUMENTATTACHMENTDOWNLOADS("DocumentAttachmentDownloads"),
    // LightningError
    LIGHTNINGERROR("LightningError"),
    // LightningInteraction
    LIGHTNINGINTERACTION("LightningInteraction"),
    // LightningPageView
    LIGHTNINGPAGEVIEW("LightningPageView"),
    // LightningPerformance
    LIGHTNINGPERFORMANCE("LightningPerformance"),
    // Login
    LOGIN("Login"),
    // LoginAs
    LOGINAS("LoginAs"),
    // Logout
    LOGOUT("Logout"),
    // MetadataApiOperation
    METADATAAPIOPERATION("MetadataApiOperation"),
    // MultiBlockReport
    MULTIBLOCKREPORT("MultiBlockReport"),
    // PackageInstall
    PACKAGEINSTALL("PackageInstall"),
    // QueuedExecution
    QUEUEDEXECUTION("QueuedExecution"),
    // Report
    REPORT("Report"),
    // ReportExport
    REPORTEXPORT("ReportExport"),
    // RestApi
    RESTAPI("RestApi"),
    // Sandbox
    SANDBOX("Sandbox"),
    // Sites
    SITES("Sites"),
    // TimeBasedWorkflow
    TIMEBASEDWORKFLOW("TimeBasedWorkflow"),
    // TransactionSecurity
    TRANSACTIONSECURITY("TransactionSecurity"),
    // UITracking
    UITRACKING("UITracking"),
    // URI
    URI("URI"),
    // VisualforceRequest
    VISUALFORCEREQUEST("VisualforceRequest"),
    // WaveChange
    WAVECHANGE("WaveChange"),
    // WaveInteraction
    WAVEINTERACTION("WaveInteraction"),
    // WavePerformance
    WAVEPERFORMANCE("WavePerformance");

    final String value;

    private EventLogFile_EventTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static EventLogFile_EventTypeEnum fromValue(String value) {
        for (EventLogFile_EventTypeEnum e : EventLogFile_EventTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
