/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject EventLogFile
 */
@XStreamAlias("EventLogFile")
public class EventLogFile extends AbstractSObjectBase {

    // EventType
    @XStreamConverter(PicklistEnumConverter.class)
    private EventLogFile_EventTypeEnum EventType;

    @JsonProperty("EventType")
    public EventLogFile_EventTypeEnum getEventType() {
        return this.EventType;
    }

    @JsonProperty("EventType")
    public void setEventType(EventLogFile_EventTypeEnum EventType) {
        this.EventType = EventType;
    }

    // LogDate
    private java.time.ZonedDateTime LogDate;

    @JsonProperty("LogDate")
    public java.time.ZonedDateTime getLogDate() {
        return this.LogDate;
    }

    @JsonProperty("LogDate")
    public void setLogDate(java.time.ZonedDateTime LogDate) {
        this.LogDate = LogDate;
    }

    // LogFileLength
    private Double LogFileLength;

    @JsonProperty("LogFileLength")
    public Double getLogFileLength() {
        return this.LogFileLength;
    }

    @JsonProperty("LogFileLength")
    public void setLogFileLength(Double LogFileLength) {
        this.LogFileLength = LogFileLength;
    }

    // LogFileContentType
    private String LogFileContentType;

    @JsonProperty("LogFileContentType")
    public String getLogFileContentType() {
        return this.LogFileContentType;
    }

    @JsonProperty("LogFileContentType")
    public void setLogFileContentType(String LogFileContentType) {
        this.LogFileContentType = LogFileContentType;
    }

    // ApiVersion
    private Double ApiVersion;

    @JsonProperty("ApiVersion")
    public Double getApiVersion() {
        return this.ApiVersion;
    }

    @JsonProperty("ApiVersion")
    public void setApiVersion(Double ApiVersion) {
        this.ApiVersion = ApiVersion;
    }

    // LogFileFieldNames
    private String LogFileFieldNames;

    @JsonProperty("LogFileFieldNames")
    public String getLogFileFieldNames() {
        return this.LogFileFieldNames;
    }

    @JsonProperty("LogFileFieldNames")
    public void setLogFileFieldNames(String LogFileFieldNames) {
        this.LogFileFieldNames = LogFileFieldNames;
    }

    // LogFileFieldTypes
    private String LogFileFieldTypes;

    @JsonProperty("LogFileFieldTypes")
    public String getLogFileFieldTypes() {
        return this.LogFileFieldTypes;
    }

    @JsonProperty("LogFileFieldTypes")
    public void setLogFileFieldTypes(String LogFileFieldTypes) {
        this.LogFileFieldTypes = LogFileFieldTypes;
    }

    // LogFile
    // blob field url, use getBlobField to get the content
    @XStreamAlias("LogFile")
    private String LogFileUrl;

    @JsonProperty("LogFile")
    public String getLogFileUrl() {
        return this.LogFileUrl;
    }

    @JsonProperty("LogFile")
    public void setLogFileUrl(String LogFileUrl) {
        this.LogFileUrl = LogFileUrl;
    }

}
