/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject Event
 */
@XStreamAlias("Event")
public class Event extends AbstractSObjectBase {

    // WhoId
    private String WhoId;

    @JsonProperty("WhoId")
    public String getWhoId() {
        return this.WhoId;
    }

    @JsonProperty("WhoId")
    public void setWhoId(String WhoId) {
        this.WhoId = WhoId;
    }

    // WhatId
    private String WhatId;

    @JsonProperty("WhatId")
    public String getWhatId() {
        return this.WhatId;
    }

    @JsonProperty("WhatId")
    public void setWhatId(String WhatId) {
        this.WhatId = WhatId;
    }

    // Subject
    private String Subject;

    @JsonProperty("Subject")
    public String getSubject() {
        return this.Subject;
    }

    @JsonProperty("Subject")
    public void setSubject(String Subject) {
        this.Subject = Subject;
    }

    // Location
    private String Location;

    @JsonProperty("Location")
    public String getLocation() {
        return this.Location;
    }

    @JsonProperty("Location")
    public void setLocation(String Location) {
        this.Location = Location;
    }

    // IsAllDayEvent
    private Boolean IsAllDayEvent;

    @JsonProperty("IsAllDayEvent")
    public Boolean getIsAllDayEvent() {
        return this.IsAllDayEvent;
    }

    @JsonProperty("IsAllDayEvent")
    public void setIsAllDayEvent(Boolean IsAllDayEvent) {
        this.IsAllDayEvent = IsAllDayEvent;
    }

    // ActivityDateTime
    private java.time.ZonedDateTime ActivityDateTime;

    @JsonProperty("ActivityDateTime")
    public java.time.ZonedDateTime getActivityDateTime() {
        return this.ActivityDateTime;
    }

    @JsonProperty("ActivityDateTime")
    public void setActivityDateTime(java.time.ZonedDateTime ActivityDateTime) {
        this.ActivityDateTime = ActivityDateTime;
    }

    // ActivityDate
    private java.time.ZonedDateTime ActivityDate;

    @JsonProperty("ActivityDate")
    public java.time.ZonedDateTime getActivityDate() {
        return this.ActivityDate;
    }

    @JsonProperty("ActivityDate")
    public void setActivityDate(java.time.ZonedDateTime ActivityDate) {
        this.ActivityDate = ActivityDate;
    }

    // DurationInMinutes
    private Integer DurationInMinutes;

    @JsonProperty("DurationInMinutes")
    public Integer getDurationInMinutes() {
        return this.DurationInMinutes;
    }

    @JsonProperty("DurationInMinutes")
    public void setDurationInMinutes(Integer DurationInMinutes) {
        this.DurationInMinutes = DurationInMinutes;
    }

    // StartDateTime
    private java.time.ZonedDateTime StartDateTime;

    @JsonProperty("StartDateTime")
    public java.time.ZonedDateTime getStartDateTime() {
        return this.StartDateTime;
    }

    @JsonProperty("StartDateTime")
    public void setStartDateTime(java.time.ZonedDateTime StartDateTime) {
        this.StartDateTime = StartDateTime;
    }

    // EndDateTime
    private java.time.ZonedDateTime EndDateTime;

    @JsonProperty("EndDateTime")
    public java.time.ZonedDateTime getEndDateTime() {
        return this.EndDateTime;
    }

    @JsonProperty("EndDateTime")
    public void setEndDateTime(java.time.ZonedDateTime EndDateTime) {
        this.EndDateTime = EndDateTime;
    }

    // Description
    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }

    // AccountId
    private String AccountId;

    @JsonProperty("AccountId")
    public String getAccountId() {
        return this.AccountId;
    }

    @JsonProperty("AccountId")
    public void setAccountId(String AccountId) {
        this.AccountId = AccountId;
    }

    // IsPrivate
    private Boolean IsPrivate;

    @JsonProperty("IsPrivate")
    public Boolean getIsPrivate() {
        return this.IsPrivate;
    }

    @JsonProperty("IsPrivate")
    public void setIsPrivate(Boolean IsPrivate) {
        this.IsPrivate = IsPrivate;
    }

    // ShowAs
    @XStreamConverter(PicklistEnumConverter.class)
    private Event_ShowAsEnum ShowAs;

    @JsonProperty("ShowAs")
    public Event_ShowAsEnum getShowAs() {
        return this.ShowAs;
    }

    @JsonProperty("ShowAs")
    public void setShowAs(Event_ShowAsEnum ShowAs) {
        this.ShowAs = ShowAs;
    }

    // IsChild
    private Boolean IsChild;

    @JsonProperty("IsChild")
    public Boolean getIsChild() {
        return this.IsChild;
    }

    @JsonProperty("IsChild")
    public void setIsChild(Boolean IsChild) {
        this.IsChild = IsChild;
    }

    // IsGroupEvent
    private Boolean IsGroupEvent;

    @JsonProperty("IsGroupEvent")
    public Boolean getIsGroupEvent() {
        return this.IsGroupEvent;
    }

    @JsonProperty("IsGroupEvent")
    public void setIsGroupEvent(Boolean IsGroupEvent) {
        this.IsGroupEvent = IsGroupEvent;
    }

    // GroupEventType
    @XStreamConverter(PicklistEnumConverter.class)
    private Event_GroupEventTypeEnum GroupEventType;

    @JsonProperty("GroupEventType")
    public Event_GroupEventTypeEnum getGroupEventType() {
        return this.GroupEventType;
    }

    @JsonProperty("GroupEventType")
    public void setGroupEventType(Event_GroupEventTypeEnum GroupEventType) {
        this.GroupEventType = GroupEventType;
    }

    // IsArchived
    private Boolean IsArchived;

    @JsonProperty("IsArchived")
    public Boolean getIsArchived() {
        return this.IsArchived;
    }

    @JsonProperty("IsArchived")
    public void setIsArchived(Boolean IsArchived) {
        this.IsArchived = IsArchived;
    }

    // RecurrenceActivityId
    private String RecurrenceActivityId;

    @JsonProperty("RecurrenceActivityId")
    public String getRecurrenceActivityId() {
        return this.RecurrenceActivityId;
    }

    @JsonProperty("RecurrenceActivityId")
    public void setRecurrenceActivityId(String RecurrenceActivityId) {
        this.RecurrenceActivityId = RecurrenceActivityId;
    }

    // IsRecurrence
    private Boolean IsRecurrence;

    @JsonProperty("IsRecurrence")
    public Boolean getIsRecurrence() {
        return this.IsRecurrence;
    }

    @JsonProperty("IsRecurrence")
    public void setIsRecurrence(Boolean IsRecurrence) {
        this.IsRecurrence = IsRecurrence;
    }

    // RecurrenceStartDateTime
    private java.time.ZonedDateTime RecurrenceStartDateTime;

    @JsonProperty("RecurrenceStartDateTime")
    public java.time.ZonedDateTime getRecurrenceStartDateTime() {
        return this.RecurrenceStartDateTime;
    }

    @JsonProperty("RecurrenceStartDateTime")
    public void setRecurrenceStartDateTime(java.time.ZonedDateTime RecurrenceStartDateTime) {
        this.RecurrenceStartDateTime = RecurrenceStartDateTime;
    }

    // RecurrenceEndDateOnly
    private java.time.ZonedDateTime RecurrenceEndDateOnly;

    @JsonProperty("RecurrenceEndDateOnly")
    public java.time.ZonedDateTime getRecurrenceEndDateOnly() {
        return this.RecurrenceEndDateOnly;
    }

    @JsonProperty("RecurrenceEndDateOnly")
    public void setRecurrenceEndDateOnly(java.time.ZonedDateTime RecurrenceEndDateOnly) {
        this.RecurrenceEndDateOnly = RecurrenceEndDateOnly;
    }

    // RecurrenceTimeZoneSidKey
    @XStreamConverter(PicklistEnumConverter.class)
    private Event_RecurrenceTimeZoneSidKeyEnum RecurrenceTimeZoneSidKey;

    @JsonProperty("RecurrenceTimeZoneSidKey")
    public Event_RecurrenceTimeZoneSidKeyEnum getRecurrenceTimeZoneSidKey() {
        return this.RecurrenceTimeZoneSidKey;
    }

    @JsonProperty("RecurrenceTimeZoneSidKey")
    public void setRecurrenceTimeZoneSidKey(Event_RecurrenceTimeZoneSidKeyEnum RecurrenceTimeZoneSidKey) {
        this.RecurrenceTimeZoneSidKey = RecurrenceTimeZoneSidKey;
    }

    // RecurrenceType
    @XStreamConverter(PicklistEnumConverter.class)
    private Event_RecurrenceTypeEnum RecurrenceType;

    @JsonProperty("RecurrenceType")
    public Event_RecurrenceTypeEnum getRecurrenceType() {
        return this.RecurrenceType;
    }

    @JsonProperty("RecurrenceType")
    public void setRecurrenceType(Event_RecurrenceTypeEnum RecurrenceType) {
        this.RecurrenceType = RecurrenceType;
    }

    // RecurrenceInterval
    private Integer RecurrenceInterval;

    @JsonProperty("RecurrenceInterval")
    public Integer getRecurrenceInterval() {
        return this.RecurrenceInterval;
    }

    @JsonProperty("RecurrenceInterval")
    public void setRecurrenceInterval(Integer RecurrenceInterval) {
        this.RecurrenceInterval = RecurrenceInterval;
    }

    // RecurrenceDayOfWeekMask
    private Integer RecurrenceDayOfWeekMask;

    @JsonProperty("RecurrenceDayOfWeekMask")
    public Integer getRecurrenceDayOfWeekMask() {
        return this.RecurrenceDayOfWeekMask;
    }

    @JsonProperty("RecurrenceDayOfWeekMask")
    public void setRecurrenceDayOfWeekMask(Integer RecurrenceDayOfWeekMask) {
        this.RecurrenceDayOfWeekMask = RecurrenceDayOfWeekMask;
    }

    // RecurrenceDayOfMonth
    private Integer RecurrenceDayOfMonth;

    @JsonProperty("RecurrenceDayOfMonth")
    public Integer getRecurrenceDayOfMonth() {
        return this.RecurrenceDayOfMonth;
    }

    @JsonProperty("RecurrenceDayOfMonth")
    public void setRecurrenceDayOfMonth(Integer RecurrenceDayOfMonth) {
        this.RecurrenceDayOfMonth = RecurrenceDayOfMonth;
    }

    // RecurrenceInstance
    @XStreamConverter(PicklistEnumConverter.class)
    private Event_RecurrenceInstanceEnum RecurrenceInstance;

    @JsonProperty("RecurrenceInstance")
    public Event_RecurrenceInstanceEnum getRecurrenceInstance() {
        return this.RecurrenceInstance;
    }

    @JsonProperty("RecurrenceInstance")
    public void setRecurrenceInstance(Event_RecurrenceInstanceEnum RecurrenceInstance) {
        this.RecurrenceInstance = RecurrenceInstance;
    }

    // RecurrenceMonthOfYear
    @XStreamConverter(PicklistEnumConverter.class)
    private Event_RecurrenceMonthOfYearEnum RecurrenceMonthOfYear;

    @JsonProperty("RecurrenceMonthOfYear")
    public Event_RecurrenceMonthOfYearEnum getRecurrenceMonthOfYear() {
        return this.RecurrenceMonthOfYear;
    }

    @JsonProperty("RecurrenceMonthOfYear")
    public void setRecurrenceMonthOfYear(Event_RecurrenceMonthOfYearEnum RecurrenceMonthOfYear) {
        this.RecurrenceMonthOfYear = RecurrenceMonthOfYear;
    }

    // ReminderDateTime
    private java.time.ZonedDateTime ReminderDateTime;

    @JsonProperty("ReminderDateTime")
    public java.time.ZonedDateTime getReminderDateTime() {
        return this.ReminderDateTime;
    }

    @JsonProperty("ReminderDateTime")
    public void setReminderDateTime(java.time.ZonedDateTime ReminderDateTime) {
        this.ReminderDateTime = ReminderDateTime;
    }

    // IsReminderSet
    private Boolean IsReminderSet;

    @JsonProperty("IsReminderSet")
    public Boolean getIsReminderSet() {
        return this.IsReminderSet;
    }

    @JsonProperty("IsReminderSet")
    public void setIsReminderSet(Boolean IsReminderSet) {
        this.IsReminderSet = IsReminderSet;
    }

}
