/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
public enum EventRelation_StatusEnum {

    // Accepted
    ACCEPTED("Accepted"),
    // Declined
    DECLINED("Declined"),
    // Maybe
    MAYBE("Maybe"),
    // New
    NEW("New"),
    // Uninvited
    UNINVITED("Uninvited");

    final String value;

    private EventRelation_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static EventRelation_StatusEnum fromValue(String value) {
        for (EventRelation_StatusEnum e : EventRelation_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
