/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject FeedPollVote
 */
@XStreamAlias("FeedPollVote")
public class FeedPollVote extends AbstractSObjectBase {

    // FeedItemId
    private String FeedItemId;

    @JsonProperty("FeedItemId")
    public String getFeedItemId() {
        return this.FeedItemId;
    }

    @JsonProperty("FeedItemId")
    public void setFeedItemId(String FeedItemId) {
        this.FeedItemId = FeedItemId;
    }

    // ChoiceId
    private String ChoiceId;

    @JsonProperty("ChoiceId")
    public String getChoiceId() {
        return this.ChoiceId;
    }

    @JsonProperty("ChoiceId")
    public void setChoiceId(String ChoiceId) {
        this.ChoiceId = ChoiceId;
    }

}
