/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist QuarterPrefix
 */
public enum FiscalYearSettings_QuarterPrefixEnum {

    // FQ
    FQ("FQ"),
    // Q
    Q("Q"),
    // Quarter
    QUARTER("Quarter"),
    // Trimester
    TRIMESTER("Trimester");

    final String value;

    private FiscalYearSettings_QuarterPrefixEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static FiscalYearSettings_QuarterPrefixEnum fromValue(String value) {
        for (FiscalYearSettings_QuarterPrefixEnum e : FiscalYearSettings_QuarterPrefixEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
