/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist YearType
 */
public enum FiscalYearSettings_YearTypeEnum {

    // Custom
    CUSTOM("Custom"),
    // Placeholder
    PLACEHOLDER("Placeholder"),
    // Standard
    STANDARD("Standard");

    final String value;

    private FiscalYearSettings_YearTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static FiscalYearSettings_YearTypeEnum fromValue(String value) {
        for (FiscalYearSettings_YearTypeEnum e : FiscalYearSettings_YearTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
