/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist AccessType
 */
public enum Folder_AccessTypeEnum {

    // Hidden
    HIDDEN("Hidden"),
    // Public
    PUBLIC("Public"),
    // PublicInternal
    PUBLICINTERNAL("PublicInternal"),
    // Shared
    SHARED("Shared");

    final String value;

    private Folder_AccessTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Folder_AccessTypeEnum fromValue(String value) {
        for (Folder_AccessTypeEnum e : Folder_AccessTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
