/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Type
 */
public enum Folder_TypeEnum {

    // Dashboard
    DASHBOARD("Dashboard"),
    // Document
    DOCUMENT("Document"),
    // Email
    EMAIL("Email"),
    // Report
    REPORT("Report");

    final String value;

    private Folder_TypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Folder_TypeEnum fromValue(String value) {
        for (Folder_TypeEnum e : Folder_TypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
