/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject Folder
 */
@XStreamAlias("Folder")
public class Folder extends AbstractSObjectBase {

    // DeveloperName
    private String DeveloperName;

    @JsonProperty("DeveloperName")
    public String getDeveloperName() {
        return this.DeveloperName;
    }

    @JsonProperty("DeveloperName")
    public void setDeveloperName(String DeveloperName) {
        this.DeveloperName = DeveloperName;
    }

    // AccessType
    @XStreamConverter(PicklistEnumConverter.class)
    private Folder_AccessTypeEnum AccessType;

    @JsonProperty("AccessType")
    public Folder_AccessTypeEnum getAccessType() {
        return this.AccessType;
    }

    @JsonProperty("AccessType")
    public void setAccessType(Folder_AccessTypeEnum AccessType) {
        this.AccessType = AccessType;
    }

    // IsReadonly
    private Boolean IsReadonly;

    @JsonProperty("IsReadonly")
    public Boolean getIsReadonly() {
        return this.IsReadonly;
    }

    @JsonProperty("IsReadonly")
    public void setIsReadonly(Boolean IsReadonly) {
        this.IsReadonly = IsReadonly;
    }

    // Type
    @XStreamConverter(PicklistEnumConverter.class)
    private Folder_TypeEnum Type;

    @JsonProperty("Type")
    public Folder_TypeEnum getType() {
        return this.Type;
    }

    @JsonProperty("Type")
    public void setType(Folder_TypeEnum Type) {
        this.Type = Type;
    }

    // NamespacePrefix
    private String NamespacePrefix;

    @JsonProperty("NamespacePrefix")
    public String getNamespacePrefix() {
        return this.NamespacePrefix;
    }

    @JsonProperty("NamespacePrefix")
    public void setNamespacePrefix(String NamespacePrefix) {
        this.NamespacePrefix = NamespacePrefix;
    }

}
