/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist RecurrenceType
 */
public enum Holiday_RecurrenceTypeEnum {

    // RecursDaily
    RECURSDAILY("RecursDaily"),
    // RecursEveryWeekday
    RECURSEVERYWEEKDAY("RecursEveryWeekday"),
    // RecursMonthly
    RECURSMONTHLY("RecursMonthly"),
    // RecursMonthlyNth
    RECURSMONTHLYNTH("RecursMonthlyNth"),
    // RecursWeekly
    RECURSWEEKLY("RecursWeekly"),
    // RecursYearly
    RECURSYEARLY("RecursYearly"),
    // RecursYearlyNth
    RECURSYEARLYNTH("RecursYearlyNth");

    final String value;

    private Holiday_RecurrenceTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Holiday_RecurrenceTypeEnum fromValue(String value) {
        for (Holiday_RecurrenceTypeEnum e : Holiday_RecurrenceTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
