/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
public enum InstalledMobileApp_StatusEnum {

    // downloaded
    DOWNLOADED("downloaded"),
    // installed
    INSTALLED("installed");

    final String value;

    private InstalledMobileApp_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static InstalledMobileApp_StatusEnum fromValue(String value) {
        for (InstalledMobileApp_StatusEnum e : InstalledMobileApp_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
