/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Salutation
 */
public enum Lead_SalutationEnum {

    // Dr.
    DR_("Dr."),
    // Mr.
    MR_("Mr."),
    // Mrs.
    MRS_("Mrs."),
    // Ms.
    MS_("Ms."),
    // Prof.
    PROF_("Prof.");

    final String value;

    private Lead_SalutationEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Lead_SalutationEnum fromValue(String value) {
        for (Lead_SalutationEnum e : Lead_SalutationEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
