/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
public enum Lead_StatusEnum {

    // Closed - Converted
    CLOSED___CONVERTED("Closed - Converted"),
    // Closed - Not Converted
    CLOSED___NOT_CONVERTED("Closed - Not Converted"),
    // Open - Not Contacted
    OPEN___NOT_CONTACTED("Open - Not Contacted"),
    // Working - Contacted
    WORKING___CONTACTED("Working - Contacted");

    final String value;

    private Lead_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Lead_StatusEnum fromValue(String value) {
        for (Lead_StatusEnum e : Lead_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
