/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject LoginIp
 */
@XStreamAlias("LoginIp")
public class LoginIp extends AbstractSObjectBase {

    // UsersId
    private String UsersId;

    @JsonProperty("UsersId")
    public String getUsersId() {
        return this.UsersId;
    }

    @JsonProperty("UsersId")
    public void setUsersId(String UsersId) {
        this.UsersId = UsersId;
    }

    // SourceIp
    private String SourceIp;

    @JsonProperty("SourceIp")
    public String getSourceIp() {
        return this.SourceIp;
    }

    @JsonProperty("SourceIp")
    public void setSourceIp(String SourceIp) {
        this.SourceIp = SourceIp;
    }

    // IsAuthenticated
    private Boolean IsAuthenticated;

    @JsonProperty("IsAuthenticated")
    public Boolean getIsAuthenticated() {
        return this.IsAuthenticated;
    }

    @JsonProperty("IsAuthenticated")
    public void setIsAuthenticated(Boolean IsAuthenticated) {
        this.IsAuthenticated = IsAuthenticated;
    }

    // ChallengeSentDate
    private java.time.ZonedDateTime ChallengeSentDate;

    @JsonProperty("ChallengeSentDate")
    public java.time.ZonedDateTime getChallengeSentDate() {
        return this.ChallengeSentDate;
    }

    @JsonProperty("ChallengeSentDate")
    public void setChallengeSentDate(java.time.ZonedDateTime ChallengeSentDate) {
        this.ChallengeSentDate = ChallengeSentDate;
    }

    // ChallengeMethod
    @XStreamConverter(PicklistEnumConverter.class)
    private LoginIp_ChallengeMethodEnum ChallengeMethod;

    @JsonProperty("ChallengeMethod")
    public LoginIp_ChallengeMethodEnum getChallengeMethod() {
        return this.ChallengeMethod;
    }

    @JsonProperty("ChallengeMethod")
    public void setChallengeMethod(LoginIp_ChallengeMethodEnum ChallengeMethod) {
        this.ChallengeMethod = ChallengeMethod;
    }

}
