/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist ActivityType
 */
public enum LookedUpFromActivity_ActivityTypeEnum {

    // Call
    CALL("Call"),
    // Email
    EMAIL("Email"),
    // Meeting
    MEETING("Meeting"),
    // Other
    OTHER("Other");

    final String value;

    private LookedUpFromActivity_ActivityTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static LookedUpFromActivity_ActivityTypeEnum fromValue(String value) {
        for (LookedUpFromActivity_ActivityTypeEnum e : LookedUpFromActivity_ActivityTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
