/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist CallType
 */
public enum LookedUpFromActivity_CallTypeEnum {

    // Inbound
    INBOUND("Inbound"),
    // Internal
    INTERNAL("Internal"),
    // Outbound
    OUTBOUND("Outbound");

    final String value;

    private LookedUpFromActivity_CallTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static LookedUpFromActivity_CallTypeEnum fromValue(String value) {
        for (LookedUpFromActivity_CallTypeEnum e : LookedUpFromActivity_CallTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
