/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject MacroShare
 */
@XStreamAlias("MacroShare")
public class MacroShare extends AbstractSObjectBase {

    // ParentId
    private String ParentId;

    @JsonProperty("ParentId")
    public String getParentId() {
        return this.ParentId;
    }

    @JsonProperty("ParentId")
    public void setParentId(String ParentId) {
        this.ParentId = ParentId;
    }

    // UserOrGroupId
    private String UserOrGroupId;

    @JsonProperty("UserOrGroupId")
    public String getUserOrGroupId() {
        return this.UserOrGroupId;
    }

    @JsonProperty("UserOrGroupId")
    public void setUserOrGroupId(String UserOrGroupId) {
        this.UserOrGroupId = UserOrGroupId;
    }

    // AccessLevel
    @XStreamConverter(PicklistEnumConverter.class)
    private MacroShare_AccessLevelEnum AccessLevel;

    @JsonProperty("AccessLevel")
    public MacroShare_AccessLevelEnum getAccessLevel() {
        return this.AccessLevel;
    }

    @JsonProperty("AccessLevel")
    public void setAccessLevel(MacroShare_AccessLevelEnum AccessLevel) {
        this.AccessLevel = AccessLevel;
    }

    // RowCause
    @XStreamConverter(PicklistEnumConverter.class)
    private MacroShare_RowCauseEnum RowCause;

    @JsonProperty("RowCause")
    public MacroShare_RowCauseEnum getRowCause() {
        return this.RowCause;
    }

    @JsonProperty("RowCause")
    public void setRowCause(MacroShare_RowCauseEnum RowCause) {
        this.RowCause = RowCause;
    }

}
