/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist BlankValueBehavior
 */
public enum MatchingRuleItem_BlankValueBehaviorEnum {

    // MatchBlanks
    MATCHBLANKS("MatchBlanks"),
    // NullNotAllowed
    NULLNOTALLOWED("NullNotAllowed");

    final String value;

    private MatchingRuleItem_BlankValueBehaviorEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static MatchingRuleItem_BlankValueBehaviorEnum fromValue(String value) {
        for (MatchingRuleItem_BlankValueBehaviorEnum e : MatchingRuleItem_BlankValueBehaviorEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
