/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject OpportunityShare
 */
@XStreamAlias("OpportunityShare")
public class OpportunityShare extends AbstractSObjectBase {

    // OpportunityId
    private String OpportunityId;

    @JsonProperty("OpportunityId")
    public String getOpportunityId() {
        return this.OpportunityId;
    }

    @JsonProperty("OpportunityId")
    public void setOpportunityId(String OpportunityId) {
        this.OpportunityId = OpportunityId;
    }

    // UserOrGroupId
    private String UserOrGroupId;

    @JsonProperty("UserOrGroupId")
    public String getUserOrGroupId() {
        return this.UserOrGroupId;
    }

    @JsonProperty("UserOrGroupId")
    public void setUserOrGroupId(String UserOrGroupId) {
        this.UserOrGroupId = UserOrGroupId;
    }

    // OpportunityAccessLevel
    @XStreamConverter(PicklistEnumConverter.class)
    private OpportunityShare_OpportunityAccessLevelEnum OpportunityAccessLevel;

    @JsonProperty("OpportunityAccessLevel")
    public OpportunityShare_OpportunityAccessLevelEnum getOpportunityAccessLevel() {
        return this.OpportunityAccessLevel;
    }

    @JsonProperty("OpportunityAccessLevel")
    public void setOpportunityAccessLevel(OpportunityShare_OpportunityAccessLevelEnum OpportunityAccessLevel) {
        this.OpportunityAccessLevel = OpportunityAccessLevel;
    }

    // RowCause
    @XStreamConverter(PicklistEnumConverter.class)
    private OpportunityShare_RowCauseEnum RowCause;

    @JsonProperty("RowCause")
    public OpportunityShare_RowCauseEnum getRowCause() {
        return this.RowCause;
    }

    @JsonProperty("RowCause")
    public void setRowCause(OpportunityShare_RowCauseEnum RowCause) {
        this.RowCause = RowCause;
    }

}
