/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist DefaultCalendarAccess
 */
public enum Organization_DefaultCalendarAccessEnum {

    // AllowEdits
    ALLOWEDITS("AllowEdits"),
    // HideDetails
    HIDEDETAILS("HideDetails"),
    // HideDetailsInsert
    HIDEDETAILSINSERT("HideDetailsInsert"),
    // ShowDetails
    SHOWDETAILS("ShowDetails"),
    // ShowDetailsInsert
    SHOWDETAILSINSERT("ShowDetailsInsert");

    final String value;

    private Organization_DefaultCalendarAccessEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Organization_DefaultCalendarAccessEnum fromValue(String value) {
        for (Organization_DefaultCalendarAccessEnum e : Organization_DefaultCalendarAccessEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
