/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist OrganizationType
 */
public enum Organization_OrganizationTypeEnum {

    // Base Edition
    BASE_EDITION("Base Edition"),
    // Contact Manager Edition
    CONTACT_MANAGER_EDITION("Contact Manager Edition"),
    // Developer Edition
    DEVELOPER_EDITION("Developer Edition"),
    // Enterprise Edition
    ENTERPRISE_EDITION("Enterprise Edition"),
    // Personal Edition
    PERSONAL_EDITION("Personal Edition"),
    // Professional Edition
    PROFESSIONAL_EDITION("Professional Edition"),
    // Team Edition
    TEAM_EDITION("Team Edition"),
    // Unlimited Edition
    UNLIMITED_EDITION("Unlimited Edition");

    final String value;

    private Organization_OrganizationTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Organization_OrganizationTypeEnum fromValue(String value) {
        for (Organization_OrganizationTypeEnum e : Organization_OrganizationTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
