/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
public enum PackageLicense_StatusEnum {

    // Active
    ACTIVE("Active"),
    // Free
    FREE("Free"),
    // Trial
    TRIAL("Trial");

    final String value;

    private PackageLicense_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static PackageLicense_StatusEnum fromValue(String value) {
        for (PackageLicense_StatusEnum e : PackageLicense_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
