/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Role
 */
public enum Partner_RoleEnum {

    // Advertiser
    ADVERTISER("Advertiser"),
    // Agency
    AGENCY("Agency"),
    // Broker
    BROKER("Broker"),
    // Consultant
    CONSULTANT("Consultant"),
    // Contractor
    CONTRACTOR("Contractor"),
    // Dealer
    DEALER("Dealer"),
    // Developer
    DEVELOPER("Developer"),
    // Distributor
    DISTRIBUTOR("Distributor"),
    // Institution
    INSTITUTION("Institution"),
    // Lender
    LENDER("Lender"),
    // Supplier
    SUPPLIER("Supplier"),
    // System Integrator
    SYSTEM_INTEGRATOR("System Integrator"),
    // VAR/Reseller
    VAR_RESELLER("VAR/Reseller");

    final String value;

    private Partner_RoleEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Partner_RoleEnum fromValue(String value) {
        for (Partner_RoleEnum e : Partner_RoleEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
