/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject Period
 */
@XStreamAlias("Period")
public class Period extends AbstractSObjectBase {

    // FiscalYearSettingsId
    private String FiscalYearSettingsId;

    @JsonProperty("FiscalYearSettingsId")
    public String getFiscalYearSettingsId() {
        return this.FiscalYearSettingsId;
    }

    @JsonProperty("FiscalYearSettingsId")
    public void setFiscalYearSettingsId(String FiscalYearSettingsId) {
        this.FiscalYearSettingsId = FiscalYearSettingsId;
    }

    // Type
    @XStreamConverter(PicklistEnumConverter.class)
    private Period_TypeEnum Type;

    @JsonProperty("Type")
    public Period_TypeEnum getType() {
        return this.Type;
    }

    @JsonProperty("Type")
    public void setType(Period_TypeEnum Type) {
        this.Type = Type;
    }

    // StartDate
    private java.time.ZonedDateTime StartDate;

    @JsonProperty("StartDate")
    public java.time.ZonedDateTime getStartDate() {
        return this.StartDate;
    }

    @JsonProperty("StartDate")
    public void setStartDate(java.time.ZonedDateTime StartDate) {
        this.StartDate = StartDate;
    }

    // EndDate
    private java.time.ZonedDateTime EndDate;

    @JsonProperty("EndDate")
    public java.time.ZonedDateTime getEndDate() {
        return this.EndDate;
    }

    @JsonProperty("EndDate")
    public void setEndDate(java.time.ZonedDateTime EndDate) {
        this.EndDate = EndDate;
    }

    // IsForecastPeriod
    private Boolean IsForecastPeriod;

    @JsonProperty("IsForecastPeriod")
    public Boolean getIsForecastPeriod() {
        return this.IsForecastPeriod;
    }

    @JsonProperty("IsForecastPeriod")
    public void setIsForecastPeriod(Boolean IsForecastPeriod) {
        this.IsForecastPeriod = IsForecastPeriod;
    }

    // QuarterLabel
    @XStreamConverter(PicklistEnumConverter.class)
    private Period_QuarterLabelEnum QuarterLabel;

    @JsonProperty("QuarterLabel")
    public Period_QuarterLabelEnum getQuarterLabel() {
        return this.QuarterLabel;
    }

    @JsonProperty("QuarterLabel")
    public void setQuarterLabel(Period_QuarterLabelEnum QuarterLabel) {
        this.QuarterLabel = QuarterLabel;
    }

    // PeriodLabel
    @XStreamConverter(PicklistEnumConverter.class)
    private Period_PeriodLabelEnum PeriodLabel;

    @JsonProperty("PeriodLabel")
    public Period_PeriodLabelEnum getPeriodLabel() {
        return this.PeriodLabel;
    }

    @JsonProperty("PeriodLabel")
    public void setPeriodLabel(Period_PeriodLabelEnum PeriodLabel) {
        this.PeriodLabel = PeriodLabel;
    }

    // Number
    private Integer Number;

    @JsonProperty("Number")
    public Integer getNumber() {
        return this.Number;
    }

    @JsonProperty("Number")
    public void setNumber(Integer Number) {
        this.Number = Number;
    }

}
