/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Category
 */
public enum PlatformAction_CategoryEnum {

    // Overflow
    OVERFLOW("Overflow"),
    // Primary
    PRIMARY("Primary");

    final String value;

    private PlatformAction_CategoryEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static PlatformAction_CategoryEnum fromValue(String value) {
        for (PlatformAction_CategoryEnum e : PlatformAction_CategoryEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
