/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist UserType
 */
public enum Profile_UserTypeEnum {

    // CsnOnly
    CSNONLY("CsnOnly"),
    // CspLitePortal
    CSPLITEPORTAL("CspLitePortal"),
    // CustomerSuccess
    CUSTOMERSUCCESS("CustomerSuccess"),
    // Guest
    GUEST("Guest"),
    // PowerCustomerSuccess
    POWERCUSTOMERSUCCESS("PowerCustomerSuccess"),
    // PowerPartner
    POWERPARTNER("PowerPartner"),
    // SelfService
    SELFSERVICE("SelfService"),
    // Standard
    STANDARD("Standard");

    final String value;

    private Profile_UserTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Profile_UserTypeEnum fromValue(String value) {
        for (Profile_UserTypeEnum e : Profile_UserTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
