/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist NotifyForFields
 */
public enum PushTopic_NotifyForFieldsEnum {

    // All
    ALL("All"),
    // Referenced
    REFERENCED("Referenced"),
    // Select
    SELECT("Select"),
    // Where
    WHERE("Where");

    final String value;

    private PushTopic_NotifyForFieldsEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static PushTopic_NotifyForFieldsEnum fromValue(String value) {
        for (PushTopic_NotifyForFieldsEnum e : PushTopic_NotifyForFieldsEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
