/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Type
 */
public enum RecentlyViewed_TypeEnum {

    // Account
    ACCOUNT("Account"),
    // Asset
    ASSET("Asset"),
    // Campaign
    CAMPAIGN("Campaign"),
    // Case
    CASE("Case"),
    // CollaborationGroup
    COLLABORATIONGROUP("CollaborationGroup"),
    // Contact
    CONTACT("Contact"),
    // ContentDocument
    CONTENTDOCUMENT("ContentDocument"),
    // Contract
    CONTRACT("Contract"),
    // Dashboard
    DASHBOARD("Dashboard"),
    // Document
    DOCUMENT("Document"),
    // DuplicateRecordSet
    DUPLICATERECORDSET("DuplicateRecordSet"),
    // Idea
    IDEA("Idea"),
    // Lead
    LEAD("Lead"),
    // ListView
    LISTVIEW("ListView"),
    // Macro
    MACRO("Macro"),
    // Opportunity
    OPPORTUNITY("Opportunity"),
    // Order
    ORDER("Order"),
    // Pricebook2
    PRICEBOOK2("Pricebook2"),
    // PricebookEntry
    PRICEBOOKENTRY("PricebookEntry"),
    // Product2
    PRODUCT2("Product2"),
    // Profile
    PROFILE("Profile"),
    // Report
    REPORT("Report"),
    // Solution
    SOLUTION("Solution"),
    // StreamingChannel
    STREAMINGCHANNEL("StreamingChannel"),
    // Topic
    TOPIC("Topic"),
    // User
    USER("User"),
    // summit__c
    SUMMIT__C("summit__c");

    final String value;

    private RecentlyViewed_TypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static RecentlyViewed_TypeEnum fromValue(String value) {
        for (RecentlyViewed_TypeEnum e : RecentlyViewed_TypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
