/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Field
 */
public enum SolutionHistory_FieldEnum {

    // IsPublished
    ISPUBLISHED("IsPublished"),
    // IsPublishedInPublicKb
    ISPUBLISHEDINPUBLICKB("IsPublishedInPublicKb"),
    // SolutionName
    SOLUTIONNAME("SolutionName"),
    // SolutionNote
    SOLUTIONNOTE("SolutionNote"),
    // Status
    STATUS("Status"),
    // created
    CREATED("created"),
    // feedEvent
    FEEDEVENT("feedEvent"),
    // locked
    LOCKED("locked"),
    // ownerAccepted
    OWNERACCEPTED("ownerAccepted"),
    // ownerAssignment
    OWNERASSIGNMENT("ownerAssignment"),
    // unlocked
    UNLOCKED("unlocked");

    final String value;

    private SolutionHistory_FieldEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static SolutionHistory_FieldEnum fromValue(String value) {
        for (SolutionHistory_FieldEnum e : SolutionHistory_FieldEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
