/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject Task
 */
@XStreamAlias("Task")
public class Task extends AbstractSObjectBase {

    // WhoId
    private String WhoId;

    @JsonProperty("WhoId")
    public String getWhoId() {
        return this.WhoId;
    }

    @JsonProperty("WhoId")
    public void setWhoId(String WhoId) {
        this.WhoId = WhoId;
    }

    // WhatId
    private String WhatId;

    @JsonProperty("WhatId")
    public String getWhatId() {
        return this.WhatId;
    }

    @JsonProperty("WhatId")
    public void setWhatId(String WhatId) {
        this.WhatId = WhatId;
    }

    // Subject
    private String Subject;

    @JsonProperty("Subject")
    public String getSubject() {
        return this.Subject;
    }

    @JsonProperty("Subject")
    public void setSubject(String Subject) {
        this.Subject = Subject;
    }

    // ActivityDate
    private java.time.ZonedDateTime ActivityDate;

    @JsonProperty("ActivityDate")
    public java.time.ZonedDateTime getActivityDate() {
        return this.ActivityDate;
    }

    @JsonProperty("ActivityDate")
    public void setActivityDate(java.time.ZonedDateTime ActivityDate) {
        this.ActivityDate = ActivityDate;
    }

    // Status
    @XStreamConverter(PicklistEnumConverter.class)
    private Task_StatusEnum Status;

    @JsonProperty("Status")
    public Task_StatusEnum getStatus() {
        return this.Status;
    }

    @JsonProperty("Status")
    public void setStatus(Task_StatusEnum Status) {
        this.Status = Status;
    }

    // Priority
    @XStreamConverter(PicklistEnumConverter.class)
    private Task_PriorityEnum Priority;

    @JsonProperty("Priority")
    public Task_PriorityEnum getPriority() {
        return this.Priority;
    }

    @JsonProperty("Priority")
    public void setPriority(Task_PriorityEnum Priority) {
        this.Priority = Priority;
    }

    // IsHighPriority
    private Boolean IsHighPriority;

    @JsonProperty("IsHighPriority")
    public Boolean getIsHighPriority() {
        return this.IsHighPriority;
    }

    @JsonProperty("IsHighPriority")
    public void setIsHighPriority(Boolean IsHighPriority) {
        this.IsHighPriority = IsHighPriority;
    }

    // Description
    private String Description;

    @JsonProperty("Description")
    public String getDescription() {
        return this.Description;
    }

    @JsonProperty("Description")
    public void setDescription(String Description) {
        this.Description = Description;
    }

    // AccountId
    private String AccountId;

    @JsonProperty("AccountId")
    public String getAccountId() {
        return this.AccountId;
    }

    @JsonProperty("AccountId")
    public void setAccountId(String AccountId) {
        this.AccountId = AccountId;
    }

    // IsClosed
    private Boolean IsClosed;

    @JsonProperty("IsClosed")
    public Boolean getIsClosed() {
        return this.IsClosed;
    }

    @JsonProperty("IsClosed")
    public void setIsClosed(Boolean IsClosed) {
        this.IsClosed = IsClosed;
    }

    // IsArchived
    private Boolean IsArchived;

    @JsonProperty("IsArchived")
    public Boolean getIsArchived() {
        return this.IsArchived;
    }

    @JsonProperty("IsArchived")
    public void setIsArchived(Boolean IsArchived) {
        this.IsArchived = IsArchived;
    }

    // CallDurationInSeconds
    private Integer CallDurationInSeconds;

    @JsonProperty("CallDurationInSeconds")
    public Integer getCallDurationInSeconds() {
        return this.CallDurationInSeconds;
    }

    @JsonProperty("CallDurationInSeconds")
    public void setCallDurationInSeconds(Integer CallDurationInSeconds) {
        this.CallDurationInSeconds = CallDurationInSeconds;
    }

    // CallType
    @XStreamConverter(PicklistEnumConverter.class)
    private Task_CallTypeEnum CallType;

    @JsonProperty("CallType")
    public Task_CallTypeEnum getCallType() {
        return this.CallType;
    }

    @JsonProperty("CallType")
    public void setCallType(Task_CallTypeEnum CallType) {
        this.CallType = CallType;
    }

    // CallDisposition
    private String CallDisposition;

    @JsonProperty("CallDisposition")
    public String getCallDisposition() {
        return this.CallDisposition;
    }

    @JsonProperty("CallDisposition")
    public void setCallDisposition(String CallDisposition) {
        this.CallDisposition = CallDisposition;
    }

    // CallObject
    private String CallObject;

    @JsonProperty("CallObject")
    public String getCallObject() {
        return this.CallObject;
    }

    @JsonProperty("CallObject")
    public void setCallObject(String CallObject) {
        this.CallObject = CallObject;
    }

    // ReminderDateTime
    private java.time.ZonedDateTime ReminderDateTime;

    @JsonProperty("ReminderDateTime")
    public java.time.ZonedDateTime getReminderDateTime() {
        return this.ReminderDateTime;
    }

    @JsonProperty("ReminderDateTime")
    public void setReminderDateTime(java.time.ZonedDateTime ReminderDateTime) {
        this.ReminderDateTime = ReminderDateTime;
    }

    // IsReminderSet
    private Boolean IsReminderSet;

    @JsonProperty("IsReminderSet")
    public Boolean getIsReminderSet() {
        return this.IsReminderSet;
    }

    @JsonProperty("IsReminderSet")
    public void setIsReminderSet(Boolean IsReminderSet) {
        this.IsReminderSet = IsReminderSet;
    }

    // RecurrenceActivityId
    private String RecurrenceActivityId;

    @JsonProperty("RecurrenceActivityId")
    public String getRecurrenceActivityId() {
        return this.RecurrenceActivityId;
    }

    @JsonProperty("RecurrenceActivityId")
    public void setRecurrenceActivityId(String RecurrenceActivityId) {
        this.RecurrenceActivityId = RecurrenceActivityId;
    }

    // IsRecurrence
    private Boolean IsRecurrence;

    @JsonProperty("IsRecurrence")
    public Boolean getIsRecurrence() {
        return this.IsRecurrence;
    }

    @JsonProperty("IsRecurrence")
    public void setIsRecurrence(Boolean IsRecurrence) {
        this.IsRecurrence = IsRecurrence;
    }

    // RecurrenceStartDateOnly
    private java.time.ZonedDateTime RecurrenceStartDateOnly;

    @JsonProperty("RecurrenceStartDateOnly")
    public java.time.ZonedDateTime getRecurrenceStartDateOnly() {
        return this.RecurrenceStartDateOnly;
    }

    @JsonProperty("RecurrenceStartDateOnly")
    public void setRecurrenceStartDateOnly(java.time.ZonedDateTime RecurrenceStartDateOnly) {
        this.RecurrenceStartDateOnly = RecurrenceStartDateOnly;
    }

    // RecurrenceEndDateOnly
    private java.time.ZonedDateTime RecurrenceEndDateOnly;

    @JsonProperty("RecurrenceEndDateOnly")
    public java.time.ZonedDateTime getRecurrenceEndDateOnly() {
        return this.RecurrenceEndDateOnly;
    }

    @JsonProperty("RecurrenceEndDateOnly")
    public void setRecurrenceEndDateOnly(java.time.ZonedDateTime RecurrenceEndDateOnly) {
        this.RecurrenceEndDateOnly = RecurrenceEndDateOnly;
    }

    // RecurrenceTimeZoneSidKey
    @XStreamConverter(PicklistEnumConverter.class)
    private Task_RecurrenceTimeZoneSidKeyEnum RecurrenceTimeZoneSidKey;

    @JsonProperty("RecurrenceTimeZoneSidKey")
    public Task_RecurrenceTimeZoneSidKeyEnum getRecurrenceTimeZoneSidKey() {
        return this.RecurrenceTimeZoneSidKey;
    }

    @JsonProperty("RecurrenceTimeZoneSidKey")
    public void setRecurrenceTimeZoneSidKey(Task_RecurrenceTimeZoneSidKeyEnum RecurrenceTimeZoneSidKey) {
        this.RecurrenceTimeZoneSidKey = RecurrenceTimeZoneSidKey;
    }

    // RecurrenceType
    @XStreamConverter(PicklistEnumConverter.class)
    private Task_RecurrenceTypeEnum RecurrenceType;

    @JsonProperty("RecurrenceType")
    public Task_RecurrenceTypeEnum getRecurrenceType() {
        return this.RecurrenceType;
    }

    @JsonProperty("RecurrenceType")
    public void setRecurrenceType(Task_RecurrenceTypeEnum RecurrenceType) {
        this.RecurrenceType = RecurrenceType;
    }

    // RecurrenceInterval
    private Integer RecurrenceInterval;

    @JsonProperty("RecurrenceInterval")
    public Integer getRecurrenceInterval() {
        return this.RecurrenceInterval;
    }

    @JsonProperty("RecurrenceInterval")
    public void setRecurrenceInterval(Integer RecurrenceInterval) {
        this.RecurrenceInterval = RecurrenceInterval;
    }

    // RecurrenceDayOfWeekMask
    private Integer RecurrenceDayOfWeekMask;

    @JsonProperty("RecurrenceDayOfWeekMask")
    public Integer getRecurrenceDayOfWeekMask() {
        return this.RecurrenceDayOfWeekMask;
    }

    @JsonProperty("RecurrenceDayOfWeekMask")
    public void setRecurrenceDayOfWeekMask(Integer RecurrenceDayOfWeekMask) {
        this.RecurrenceDayOfWeekMask = RecurrenceDayOfWeekMask;
    }

    // RecurrenceDayOfMonth
    private Integer RecurrenceDayOfMonth;

    @JsonProperty("RecurrenceDayOfMonth")
    public Integer getRecurrenceDayOfMonth() {
        return this.RecurrenceDayOfMonth;
    }

    @JsonProperty("RecurrenceDayOfMonth")
    public void setRecurrenceDayOfMonth(Integer RecurrenceDayOfMonth) {
        this.RecurrenceDayOfMonth = RecurrenceDayOfMonth;
    }

    // RecurrenceInstance
    @XStreamConverter(PicklistEnumConverter.class)
    private Task_RecurrenceInstanceEnum RecurrenceInstance;

    @JsonProperty("RecurrenceInstance")
    public Task_RecurrenceInstanceEnum getRecurrenceInstance() {
        return this.RecurrenceInstance;
    }

    @JsonProperty("RecurrenceInstance")
    public void setRecurrenceInstance(Task_RecurrenceInstanceEnum RecurrenceInstance) {
        this.RecurrenceInstance = RecurrenceInstance;
    }

    // RecurrenceMonthOfYear
    @XStreamConverter(PicklistEnumConverter.class)
    private Task_RecurrenceMonthOfYearEnum RecurrenceMonthOfYear;

    @JsonProperty("RecurrenceMonthOfYear")
    public Task_RecurrenceMonthOfYearEnum getRecurrenceMonthOfYear() {
        return this.RecurrenceMonthOfYear;
    }

    @JsonProperty("RecurrenceMonthOfYear")
    public void setRecurrenceMonthOfYear(Task_RecurrenceMonthOfYearEnum RecurrenceMonthOfYear) {
        this.RecurrenceMonthOfYear = RecurrenceMonthOfYear;
    }

    // RecurrenceRegeneratedType
    @XStreamConverter(PicklistEnumConverter.class)
    private Task_RecurrenceRegeneratedTypeEnum RecurrenceRegeneratedType;

    @JsonProperty("RecurrenceRegeneratedType")
    public Task_RecurrenceRegeneratedTypeEnum getRecurrenceRegeneratedType() {
        return this.RecurrenceRegeneratedType;
    }

    @JsonProperty("RecurrenceRegeneratedType")
    public void setRecurrenceRegeneratedType(Task_RecurrenceRegeneratedTypeEnum RecurrenceRegeneratedType) {
        this.RecurrenceRegeneratedType = RecurrenceRegeneratedType;
    }

}
