/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject TenantUsageEntitlement
 */
@XStreamAlias("TenantUsageEntitlement")
public class TenantUsageEntitlement extends AbstractSObjectBase {

    // ResourceGroupKey
    private String ResourceGroupKey;

    @JsonProperty("ResourceGroupKey")
    public String getResourceGroupKey() {
        return this.ResourceGroupKey;
    }

    @JsonProperty("ResourceGroupKey")
    public void setResourceGroupKey(String ResourceGroupKey) {
        this.ResourceGroupKey = ResourceGroupKey;
    }

    // Setting
    private String Setting;

    @JsonProperty("Setting")
    public String getSetting() {
        return this.Setting;
    }

    @JsonProperty("Setting")
    public void setSetting(String Setting) {
        this.Setting = Setting;
    }

    // StartDate
    private java.time.ZonedDateTime StartDate;

    @JsonProperty("StartDate")
    public java.time.ZonedDateTime getStartDate() {
        return this.StartDate;
    }

    @JsonProperty("StartDate")
    public void setStartDate(java.time.ZonedDateTime StartDate) {
        this.StartDate = StartDate;
    }

    // EndDate
    private java.time.ZonedDateTime EndDate;

    @JsonProperty("EndDate")
    public java.time.ZonedDateTime getEndDate() {
        return this.EndDate;
    }

    @JsonProperty("EndDate")
    public void setEndDate(java.time.ZonedDateTime EndDate) {
        this.EndDate = EndDate;
    }

    // CurrentAmountAllowed
    private Double CurrentAmountAllowed;

    @JsonProperty("CurrentAmountAllowed")
    public Double getCurrentAmountAllowed() {
        return this.CurrentAmountAllowed;
    }

    @JsonProperty("CurrentAmountAllowed")
    public void setCurrentAmountAllowed(Double CurrentAmountAllowed) {
        this.CurrentAmountAllowed = CurrentAmountAllowed;
    }

    // Frequency
    @XStreamConverter(PicklistEnumConverter.class)
    private TenantUsageEntitlement_FrequencyEnum Frequency;

    @JsonProperty("Frequency")
    public TenantUsageEntitlement_FrequencyEnum getFrequency() {
        return this.Frequency;
    }

    @JsonProperty("Frequency")
    public void setFrequency(TenantUsageEntitlement_FrequencyEnum Frequency) {
        this.Frequency = Frequency;
    }

    // IsPersistentResource
    private Boolean IsPersistentResource;

    @JsonProperty("IsPersistentResource")
    public Boolean getIsPersistentResource() {
        return this.IsPersistentResource;
    }

    @JsonProperty("IsPersistentResource")
    public void setIsPersistentResource(Boolean IsPersistentResource) {
        this.IsPersistentResource = IsPersistentResource;
    }

    // HasRollover
    private Boolean HasRollover;

    @JsonProperty("HasRollover")
    public Boolean getHasRollover() {
        return this.HasRollover;
    }

    @JsonProperty("HasRollover")
    public void setHasRollover(Boolean HasRollover) {
        this.HasRollover = HasRollover;
    }

    // OverageGrace
    private Double OverageGrace;

    @JsonProperty("OverageGrace")
    public Double getOverageGrace() {
        return this.OverageGrace;
    }

    @JsonProperty("OverageGrace")
    public void setOverageGrace(Double OverageGrace) {
        this.OverageGrace = OverageGrace;
    }

    // AmountUsed
    private Double AmountUsed;

    @JsonProperty("AmountUsed")
    public Double getAmountUsed() {
        return this.AmountUsed;
    }

    @JsonProperty("AmountUsed")
    public void setAmountUsed(Double AmountUsed) {
        this.AmountUsed = AmountUsed;
    }

    // UsageDate
    private java.time.ZonedDateTime UsageDate;

    @JsonProperty("UsageDate")
    public java.time.ZonedDateTime getUsageDate() {
        return this.UsageDate;
    }

    @JsonProperty("UsageDate")
    public void setUsageDate(java.time.ZonedDateTime UsageDate) {
        this.UsageDate = UsageDate;
    }

    // MasterLabel
    private String MasterLabel;

    @JsonProperty("MasterLabel")
    public String getMasterLabel() {
        return this.MasterLabel;
    }

    @JsonProperty("MasterLabel")
    public void setMasterLabel(String MasterLabel) {
        this.MasterLabel = MasterLabel;
    }

}
