/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist PortalType
 */
public enum UserRole_PortalTypeEnum {

    // CustomerPortal
    CUSTOMERPORTAL("CustomerPortal"),
    // None
    NONE("None"),
    // Partner
    PARTNER("Partner");

    final String value;

    private UserRole_PortalTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static UserRole_PortalTypeEnum fromValue(String value) {
        for (UserRole_PortalTypeEnum e : UserRole_PortalTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
