/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject UserShare
 */
@XStreamAlias("UserShare")
public class UserShare extends AbstractSObjectBase {

    // UserId
    private String UserId;

    @JsonProperty("UserId")
    public String getUserId() {
        return this.UserId;
    }

    @JsonProperty("UserId")
    public void setUserId(String UserId) {
        this.UserId = UserId;
    }

    // UserOrGroupId
    private String UserOrGroupId;

    @JsonProperty("UserOrGroupId")
    public String getUserOrGroupId() {
        return this.UserOrGroupId;
    }

    @JsonProperty("UserOrGroupId")
    public void setUserOrGroupId(String UserOrGroupId) {
        this.UserOrGroupId = UserOrGroupId;
    }

    // UserAccessLevel
    @XStreamConverter(PicklistEnumConverter.class)
    private UserShare_UserAccessLevelEnum UserAccessLevel;

    @JsonProperty("UserAccessLevel")
    public UserShare_UserAccessLevelEnum getUserAccessLevel() {
        return this.UserAccessLevel;
    }

    @JsonProperty("UserAccessLevel")
    public void setUserAccessLevel(UserShare_UserAccessLevelEnum UserAccessLevel) {
        this.UserAccessLevel = UserAccessLevel;
    }

    // RowCause
    @XStreamConverter(PicklistEnumConverter.class)
    private UserShare_RowCauseEnum RowCause;

    @JsonProperty("RowCause")
    public UserShare_RowCauseEnum getRowCause() {
        return this.RowCause;
    }

    @JsonProperty("RowCause")
    public void setRowCause(UserShare_RowCauseEnum RowCause) {
        this.RowCause = RowCause;
    }

    // IsActive
    private Boolean IsActive;

    @JsonProperty("IsActive")
    public Boolean getIsActive() {
        return this.IsActive;
    }

    @JsonProperty("IsActive")
    public void setIsActive(Boolean IsActive) {
        this.IsActive = IsActive;
    }

}
