/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject UserListView
 */
@XStreamAlias("UserListView")
public class UserListView extends AbstractSObjectBase {

    // UserId
    private String UserId;

    @JsonProperty("UserId")
    public String getUserId() {
        return this.UserId;
    }

    @JsonProperty("UserId")
    public void setUserId(String UserId) {
        this.UserId = UserId;
    }

    // ListViewId
    private String ListViewId;

    @JsonProperty("ListViewId")
    public String getListViewId() {
        return this.ListViewId;
    }

    @JsonProperty("ListViewId")
    public void setListViewId(String ListViewId) {
        this.ListViewId = ListViewId;
    }

    // SobjectType
    @XStreamConverter(PicklistEnumConverter.class)
    private UserListView_SobjectTypeEnum SobjectType;

    @JsonProperty("SobjectType")
    public UserListView_SobjectTypeEnum getSobjectType() {
        return this.SobjectType;
    }

    @JsonProperty("SobjectType")
    public void setSobjectType(UserListView_SobjectTypeEnum SobjectType) {
        this.SobjectType = SobjectType;
    }

    // LastViewedChart
    @XStreamConverter(PicklistEnumConverter.class)
    private UserListView_LastViewedChartEnum LastViewedChart;

    @JsonProperty("LastViewedChart")
    public UserListView_LastViewedChartEnum getLastViewedChart() {
        return this.LastViewedChart;
    }

    @JsonProperty("LastViewedChart")
    public void setLastViewedChart(UserListView_LastViewedChartEnum LastViewedChart) {
        this.LastViewedChart = LastViewedChart;
    }

}
