/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist LinkState
 */
public enum UserProvAccount_LinkStateEnum {

    // Duplicate
    DUPLICATE("Duplicate"),
    // Ignored
    IGNORED("Ignored"),
    // Linked
    LINKED("Linked"),
    // Orphaned
    ORPHANED("Orphaned");

    final String value;

    private UserProvAccount_LinkStateEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static UserProvAccount_LinkStateEnum fromValue(String value) {
        for (UserProvAccount_LinkStateEnum e : UserProvAccount_LinkStateEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
