/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Operation
 */
public enum UserListViewCriterion_OperationEnum {

    // contains
    CONTAINS("contains"),
    // equals
    EQUALS("equals"),
    // includes
    INCLUDES("includes"),
    // rangeInclusive
    RANGEINCLUSIVE("rangeInclusive"),
    // startsWith
    STARTSWITH("startsWith");

    final String value;

    private UserListViewCriterion_OperationEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static UserListViewCriterion_OperationEnum fromValue(String value) {
        for (UserListViewCriterion_OperationEnum e : UserListViewCriterion_OperationEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
