/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Apr 14 20:48:00 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist PageOrSobjectType
 */
public enum WebLink_PageOrSobjectTypeEnum {

    // Account
    ACCOUNT("Account"),
    // Activity
    ACTIVITY("Activity"),
    // Asset
    ASSET("Asset"),
    // Campaign
    CAMPAIGN("Campaign"),
    // CampaignMember
    CAMPAIGNMEMBER("CampaignMember"),
    // Case
    CASE("Case"),
    // Contact
    CONTACT("Contact"),
    // ContentVersion
    CONTENTVERSION("ContentVersion"),
    // Contract
    CONTRACT("Contract"),
    // CustomPageItem
    CUSTOMPAGEITEM("CustomPageItem"),
    // DandBCompany
    DANDBCOMPANY("DandBCompany"),
    // DashboardComponent
    DASHBOARDCOMPONENT("DashboardComponent"),
    // DuplicateRecordItem
    DUPLICATERECORDITEM("DuplicateRecordItem"),
    // DuplicateRecordSet
    DUPLICATERECORDSET("DuplicateRecordSet"),
    // EmailMessage
    EMAILMESSAGE("EmailMessage"),
    // Event
    EVENT("Event"),
    // Goal
    GOAL("Goal"),
    // GoalLink
    GOALLINK("GoalLink"),
    // Idea
    IDEA("Idea"),
    // Lead
    LEAD("Lead"),
    // Macro
    MACRO("Macro"),
    // Metric
    METRIC("Metric"),
    // Opportunity
    OPPORTUNITY("Opportunity"),
    // OpportunityLineItem
    OPPORTUNITYLINEITEM("OpportunityLineItem"),
    // Order
    ORDER("Order"),
    // OrderItem
    ORDERITEM("OrderItem"),
    // Product2
    PRODUCT2("Product2"),
    // SocialPersona
    SOCIALPERSONA("SocialPersona"),
    // Solution
    SOLUTION("Solution"),
    // Task
    TASK("Task"),
    // User
    USER("User"),
    // UserProvisioningRequest
    USERPROVISIONINGREQUEST("UserProvisioningRequest"),
    // WorkCoaching
    WORKCOACHING("WorkCoaching"),
    // WorkFeedback
    WORKFEEDBACK("WorkFeedback"),
    // WorkFeedbackQuestion
    WORKFEEDBACKQUESTION("WorkFeedbackQuestion"),
    // WorkFeedbackQuestionSet
    WORKFEEDBACKQUESTIONSET("WorkFeedbackQuestionSet"),
    // WorkFeedbackRequest
    WORKFEEDBACKREQUEST("WorkFeedbackRequest"),
    // WorkFeedbackTemplate
    WORKFEEDBACKTEMPLATE("WorkFeedbackTemplate"),
    // WorkPerformanceCycle
    WORKPERFORMANCECYCLE("WorkPerformanceCycle"),
    // summit__c
    SUMMIT__C("summit__c");

    final String value;

    private WebLink_PageOrSobjectTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static WebLink_PageOrSobjectTypeEnum fromValue(String value) {
        for (WebLink_PageOrSobjectTypeEnum e : WebLink_PageOrSobjectTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
