/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Sun Apr 16 12:59:17 EDT 2017
 */
package com.redhat.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject ObjectPermissions
 */
@XStreamAlias("ObjectPermissions")
public class ObjectPermissions extends AbstractSObjectBase {

    // ParentId
    private String ParentId;

    @JsonProperty("ParentId")
    public String getParentId() {
        return this.ParentId;
    }

    @JsonProperty("ParentId")
    public void setParentId(String ParentId) {
        this.ParentId = ParentId;
    }

    // SobjectType
    @XStreamConverter(PicklistEnumConverter.class)
    private ObjectPermissions_SobjectTypeEnum SobjectType;

    @JsonProperty("SobjectType")
    public ObjectPermissions_SobjectTypeEnum getSobjectType() {
        return this.SobjectType;
    }

    @JsonProperty("SobjectType")
    public void setSobjectType(ObjectPermissions_SobjectTypeEnum SobjectType) {
        this.SobjectType = SobjectType;
    }

    // PermissionsCreate
    private Boolean PermissionsCreate;

    @JsonProperty("PermissionsCreate")
    public Boolean getPermissionsCreate() {
        return this.PermissionsCreate;
    }

    @JsonProperty("PermissionsCreate")
    public void setPermissionsCreate(Boolean PermissionsCreate) {
        this.PermissionsCreate = PermissionsCreate;
    }

    // PermissionsRead
    private Boolean PermissionsRead;

    @JsonProperty("PermissionsRead")
    public Boolean getPermissionsRead() {
        return this.PermissionsRead;
    }

    @JsonProperty("PermissionsRead")
    public void setPermissionsRead(Boolean PermissionsRead) {
        this.PermissionsRead = PermissionsRead;
    }

    // PermissionsEdit
    private Boolean PermissionsEdit;

    @JsonProperty("PermissionsEdit")
    public Boolean getPermissionsEdit() {
        return this.PermissionsEdit;
    }

    @JsonProperty("PermissionsEdit")
    public void setPermissionsEdit(Boolean PermissionsEdit) {
        this.PermissionsEdit = PermissionsEdit;
    }

    // PermissionsDelete
    private Boolean PermissionsDelete;

    @JsonProperty("PermissionsDelete")
    public Boolean getPermissionsDelete() {
        return this.PermissionsDelete;
    }

    @JsonProperty("PermissionsDelete")
    public void setPermissionsDelete(Boolean PermissionsDelete) {
        this.PermissionsDelete = PermissionsDelete;
    }

    // PermissionsViewAllRecords
    private Boolean PermissionsViewAllRecords;

    @JsonProperty("PermissionsViewAllRecords")
    public Boolean getPermissionsViewAllRecords() {
        return this.PermissionsViewAllRecords;
    }

    @JsonProperty("PermissionsViewAllRecords")
    public void setPermissionsViewAllRecords(Boolean PermissionsViewAllRecords) {
        this.PermissionsViewAllRecords = PermissionsViewAllRecords;
    }

    // PermissionsModifyAllRecords
    private Boolean PermissionsModifyAllRecords;

    @JsonProperty("PermissionsModifyAllRecords")
    public Boolean getPermissionsModifyAllRecords() {
        return this.PermissionsModifyAllRecords;
    }

    @JsonProperty("PermissionsModifyAllRecords")
    public void setPermissionsModifyAllRecords(Boolean PermissionsModifyAllRecords) {
        this.PermissionsModifyAllRecords = PermissionsModifyAllRecords;
    }

}
