/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 * Generated on: Sun Apr 16 12:59:17 EDT 2017
 */
package com.redhat.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamImplicit;
import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;

/**
 * Salesforce QueryRecords DTO for type ObjectPermissions
 */
public class QueryRecordsObjectPermissions extends AbstractQueryRecordsBase {

    @XStreamImplicit
    private List<ObjectPermissions> records;

    public List<ObjectPermissions> getRecords() {
        return records;
    }

    public void setRecords(List<ObjectPermissions> records) {
        this.records = records;
    }
}
